PizzaApp/Controllers/AddressController.cs
using PizzaApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PizzaApp.Controllers
{
    public class AddressController : Controller
    {
        public PizzaAppContext _context;

        public AddressController()
        {
            this._context = new PizzaAppContext();
        }

        protected override void Dispose(bool disposing)
        {
            this._context.Dispose();
        }

        // GET: Address
        public ActionResult New(int id)
        {
            Address address = new Address();
            address.GusetId = id;
            return View(address);
        }

        public ActionResult Save(Address address)
        {
            if (address == null)
                return HttpNotFound();

            _context.Addresses.Add(address);
            _context.SaveChanges();

            Guest guest = _context.Guests.Where(g => g.Id == address.GusetId).SingleOrDefault();

            return RedirectToAction("ShowGuest", "Guest", new {guest.Id});
        }
    }
}

PizzaApp/Views/Address/New.cshtml
@model PizzaApp.Models.Address

@{
    ViewBag.Title = "New";
}

<h2>Cím</h2>

@using (Html.BeginForm("Save", "Address"))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Cím hozzáadás</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(a => a.GuestAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(a => a.GuestAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(a => a.GuestAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor( a => a.GusetId);

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Mentés" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>