PizzaApp/Controllers/DelivererController.cs
using PizzaApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PizzaApp.Controllers
{
    public class DelivererController : Controller
    {
        public PizzaAppContext _context;

        public DelivererController()
        {
            this._context = new PizzaAppContext();
        }

        protected override void Dispose(bool disposing)
        {
            this._context.Dispose();
        }
        // GET: Deliverer
        public ActionResult Index()
        {
            List<Deliverer> deliverers = _context.Deliverers.ToList();
            return View(deliverers);
        }

        public ActionResult Send(int id)
        {
            Deliverer delivererInDB = _context.Deliverers.Where(x => x.Id == id).SingleOrDefault();

            List<Order> orders = _context
                    .Orders
                    .Where(o => o.Status == StatusName.VaitingForDelivering
                    || o.Status == StatusName.Active)                    
                    .ToList();

            if (delivererInDB.IsOnWay == false)
            {
                foreach (Order order in orders)
                {
                    if(order.Status == StatusName.VaitingForDelivering && order.DelivererId == delivererInDB.Id)
                    {
                        order.Status = StatusName.Active;
                    }
                }
                delivererInDB.IsOnWay = true;
            }
            else
            {
                foreach (Order order in orders)
                {
                    if (order.Status == StatusName.Active && order.DelivererId == delivererInDB.Id)
                    {
                        order.Status = StatusName.Delivered;
                    }
                }
                if(delivererInDB.IsFull == true)                
                    delivererInDB.IsFull = false;
                
                delivererInDB.IsOnWay = false;
            }

            _context.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

PizzaApp/Controllers/GuestController.cs
using PizzaApp.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PizzaApp.Controllers
{
    public class GuestController : Controller
    {

        public PizzaAppContext _context;

        public GuestController()
        {
            this._context = new PizzaAppContext();
        }

        protected override void Dispose(bool disposing)
        {
            this._context.Dispose();
        }

        public ActionResult ShowGuest(int id)
        {
            List<Address> addresses = _context.Addresses.Where(a => a.GusetId == id).ToList();
            Guest guest = _context.Guests.Where(g => g.Id == id).SingleOrDefault();
            guest.Addresses = addresses;

            if (guest == null)
                return HttpNotFound();

            return View(guest);
        }

        public ActionResult Register()
        {
            return View();
        }

        public ActionResult Save(Guest guest)
        {
            if (guest == null)
                return HttpNotFound();

            _context.Guests.Add(guest);
            _context.SaveChanges();

            return RedirectToAction("New", "Address", new { guest.Id });
        }
    }
}

PizzaApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Pizza app", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">                 
                    <li>@Html.ActionLink("Vendég keresése", "Index", "Ordering")</li>                    
                    <li>@Html.ActionLink("Aktív rendelések", "ActiveOrders", "Home")</li>                    
                    <li>@Html.ActionLink("Összes rendelés", "AllOrders", "Home")</li>                    
                    <li>@Html.ActionLink("Új személy regisztrálás", "Register", "Guest")</li>                    
                    <li>@Html.ActionLink("Futárok", "Index", "Deliverer")</li>                    
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>